-- AlterTable
ALTER TABLE "User" ALTER COLUMN "customerId" DROP NOT NULL,
ALTER COLUMN "subscriptionId" DROP NOT NULL,
ALTER COLUMN "plan_name" DROP NOT NULL,
ALTER COLUMN "period_ends" DROP NOT NULL,
ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "resetToken" DROP NOT NULL,
ALTER COLUMN "resetTokenExpiry" DROP NOT NULL;
